### ISSUE TITLE
Problem building Windows binary

### ISSUE THREAD

**Issue by SoftwUser** [lesspass/lesspass#201]
Follow up to #200 

Although I am perfectly fine with using the Chrome extension offline, I felt encouraged to try the desktop version.
However I failed to build the Windows binaries, being not an expert for building binaries.
I do have some experience using NodeJS/NPM, though.
I have installed  https://nodejs.org/dist/v7.8.0/node-v7.8.0-x64.msi  on my system.

Before I spam this issue with the error message/log, please tell me 

- do I need NodeJS to build this?
- do I need "electron"? If yes, can you please point me to the correct installation file for Windows 64bit? I don't need anything else than the required files for building Lesspass Desktop.

Thank you!

**Comment by guillaumevincent** [comment]
`npm install` and `npm run build` and logs inside <details> tags

**Comment by SoftwUser** [comment]
Ok, so `npm install` seems to work just fine

`npm run build:windows` returns some errors.

This is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:windows' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose run-script [ 'prebuild:windows', 'build:windows', 'postbuild:windows' ]
5 info lifecycle lesspass-desktop@1.0.0~prebuild:windows: lesspass-desktop@1.0.0
6 silly lifecycle lesspass-desktop@1.0.0~prebuild:windows: no script for prebuild:windows, continuing
7 info lifecycle lesspass-desktop@1.0.0~build:windows: lesspass-desktop@1.0.0
8 verbose lifecycle lesspass-desktop@1.0.0~build:windows: unsafe-perm in lifecycle true
9 verbose lifecycle lesspass-desktop@1.0.0~build:windows: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Tools\LessPass\node_modules\.bin;C:\Users\User\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\nodejs\;C:\Users\User\AppData\Roaming\npm
10 verbose lifecycle lesspass-desktop@1.0.0~build:windows: CWD: C:\Tools\LessPass
11 silly lifecycle lesspass-desktop@1.0.0~build:windows: Args: [ '/d /s /c',
11 silly lifecycle   'npm run build && electron-packager ./ --platform=win32 --arch=x64 --icon=images/icon.ico --ignore=node_modules --overwrite && python zip.py' ]
12 silly lifecycle lesspass-desktop@1.0.0~build:windows: Returned: code: 1  signal: null
13 info lifecycle lesspass-desktop@1.0.0~build:windows: Failed to exec build:windows script
14 verbose stack Error: lesspass-desktop@1.0.0 build:windows: `npm run build && electron-packager ./ --platform=win32 --arch=x64 --icon=images/icon.ico --ignore=node_modules --overwrite && python zip.py`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid lesspass-desktop@1.0.0
16 verbose cwd C:\Tools\LessPass
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:windows"
19 error node v7.8.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error lesspass-desktop@1.0.0 build:windows: `npm run build && electron-packager ./ --platform=win32 --arch=x64 --icon=images/icon.ico --ignore=node_modules --overwrite && python zip.py`
23 error Exit status 1
24 error Failed at the lesspass-desktop@1.0.0 build:windows script 'npm run build && electron-packager ./ --platform=win32 --arch=x64 --icon=images/icon.ico --ignore=node_modules --overwrite && python zip.py'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the lesspass-desktop package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run build && electron-packager ./ --platform=win32 --arch=x64 --icon=images/icon.ico --ignore=node_modules --overwrite && python zip.py
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs lesspass-desktop
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls lesspass-desktop
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

What do you mean by `logs inside <details></details> tags` ?

**Comment by SoftwUser** [comment]
@guillaumevincent 

Also I wonder if it is normal, that this process creates more than 300 MB of Data on my harddrive of which 133 MB are inside the newly created folder `LessPass-win32-x64` ?

**Comment by guillaumevincent** [comment]
welcome in electron world :(
It download chrome v8 engine, node and a lot of stuff

It seems you are trying to build it on windows
I will see next week if electron-packager got some updates

**Comment by guillaumevincent** [comment]
@SoftwUser I updated electron-packager can you try again to see if there is some improvement?

**Comment by SoftwUser** [comment]
@guillaumevincent 

Thanky you. Unfortunately it still does not work. I tested again and still get problems when `npm run build:windows` .
This is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:windows' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose run-script [ 'prebuild:windows', 'build:windows', 'postbuild:windows' ]
5 info lifecycle lesspass-desktop@1.0.0~prebuild:windows: lesspass-desktop@1.0.0
6 silly lifecycle lesspass-desktop@1.0.0~prebuild:windows: no script for prebuild:windows, continuing
7 info lifecycle lesspass-desktop@1.0.0~build:windows: lesspass-desktop@1.0.0
8 verbose lifecycle lesspass-desktop@1.0.0~build:windows: unsafe-perm in lifecycle true
9 verbose lifecycle lesspass-desktop@1.0.0~build:windows: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Tools\LessPass\node_modules\.bin;C:\Users\User\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\nodejs\;C:\Users\User\AppData\Roaming\npm
10 verbose lifecycle lesspass-desktop@1.0.0~build:windows: CWD: C:\Tools\LessPass
11 silly lifecycle lesspass-desktop@1.0.0~build:windows: Args: [ '/d /s /c',
11 silly lifecycle   'npm run build && electron-packager ./ --platform=win32 --arch=x64 --icon=images/icon.ico --ignore=node_modules --overwrite && python zip.py' ]
12 silly lifecycle lesspass-desktop@1.0.0~build:windows: Returned: code: 1  signal: null
13 info lifecycle lesspass-desktop@1.0.0~build:windows: Failed to exec build:windows script
14 verbose stack Error: lesspass-desktop@1.0.0 build:windows: `npm run build && electron-packager ./ --platform=win32 --arch=x64 --icon=images/icon.ico --ignore=node_modules --overwrite && python zip.py`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid lesspass-desktop@1.0.0
16 verbose cwd C:\Tools\LessPass
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:windows"
19 error node v7.8.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error lesspass-desktop@1.0.0 build:windows: `npm run build && electron-packager ./ --platform=win32 --arch=x64 --icon=images/icon.ico --ignore=node_modules --overwrite && python zip.py`
23 error Exit status 1
24 error Failed at the lesspass-desktop@1.0.0 build:windows script 'npm run build && electron-packager ./ --platform=win32 --arch=x64 --icon=images/icon.ico --ignore=node_modules --overwrite && python zip.py'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the lesspass-desktop package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run build && electron-packager ./ --platform=win32 --arch=x64 --icon=images/icon.ico --ignore=node_modules --overwrite && python zip.py
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs lesspass-desktop
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls lesspass-desktop
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

Also I noticed something not written in the log, but showing in the Node.js command-prompt window:

A message (translated from my native language) saying something similar to

> The command "python" has either been written incorrectly or could not been found

I hope that helps...

**Comment by guillaumevincent** [comment]
Ah maybe it's only the bundle in python 
Does LessPass.exe in the build folder works?

**Comment by SoftwUser** [comment]
Well I can execute it, but I don't get anything else than this:

![test](https://cloud.githubusercontent.com/assets/26350225/24840991/c3ec98c8-1d79-11e7-9e92-bb500823ed21.PNG)

Nothing I can do there...

**Comment by guillaumevincent** [comment]
@SoftwUser a found an error in vue-polyglot
Thank you for your tests, it's now fixed, you can `npm run build:windows` and LessPass Desktop

**Comment by SoftwUser** [comment]
@guillaumevincent 

I confirm it works like a breeze, now! Thank you!
