### ISSUE TITLE
SMTP Connection refused

### ISSUE THREAD

**Issue by maxguru** [lesspass/lesspass#202]
I tried to set up lesspass in my docker environment but I am getting the following in the backend container logs,

```
4/6/2017 5:50:01 PMTraceback (most recent call last):
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
4/6/2017 5:50:01 PM    self.handle_request(listener, req, client, addr)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
4/6/2017 5:50:01 PM    six.reraise(*sys.exc_info())
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/gunicorn/six.py", line 625, in reraise
4/6/2017 5:50:01 PM    raise value
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
4/6/2017 5:50:01 PM    respiter = self.wsgi(environ, resp.start_response)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
4/6/2017 5:50:01 PM    response = self.get_response(request)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response
4/6/2017 5:50:01 PM    response = self._middleware_chain(request)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 44, in inner
4/6/2017 5:50:01 PM    response = response_for_exception(request, exc)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 94, in response_for_exception
4/6/2017 5:50:01 PM    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 132, in handle_uncaught_exception
4/6/2017 5:50:01 PM    extra={'status_code': 500, 'request': request},
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/logging/__init__.py", line 1309, in error
4/6/2017 5:50:01 PM    self._log(ERROR, msg, args, **kwargs)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/logging/__init__.py", line 1416, in _log
4/6/2017 5:50:01 PM    self.handle(record)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/logging/__init__.py", line 1426, in handle
4/6/2017 5:50:01 PM    self.callHandlers(record)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/logging/__init__.py", line 1488, in callHandlers
4/6/2017 5:50:01 PM    hdlr.handle(record)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/logging/__init__.py", line 856, in handle
4/6/2017 5:50:01 PM    self.emit(record)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/django/utils/log.py", line 121, in emit
4/6/2017 5:50:01 PM    self.send_mail(subject, message, fail_silently=True, html_message=html_message)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/django/utils/log.py", line 124, in send_mail
4/6/2017 5:50:01 PM    mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/django/core/mail/__init__.py", line 103, in mail_admins
4/6/2017 5:50:01 PM    mail.send(fail_silently=fail_silently)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/django/core/mail/message.py", line 342, in send
4/6/2017 5:50:01 PM    return self.get_connection(fail_silently).send_messages([self])
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
4/6/2017 5:50:01 PM    new_conn_created = self.open()
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 58, in open
4/6/2017 5:50:01 PM    self.connection = connection_class(self.host, self.port, **connection_params)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/smtplib.py", line 251, in __init__
4/6/2017 5:50:01 PM    (code, msg) = self.connect(host, port)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/smtplib.py", line 335, in connect
4/6/2017 5:50:01 PM    self.sock = self._get_socket(host, port, self.timeout)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/smtplib.py", line 306, in _get_socket
4/6/2017 5:50:01 PM    self.source_address)
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/socket.py", line 712, in create_connection
4/6/2017 5:50:01 PM    raise err
4/6/2017 5:50:01 PM  File "/usr/local/lib/python3.5/socket.py", line 703, in create_connection
4/6/2017 5:50:01 PM    sock.connect(sa)
4/6/2017 5:50:01 PMConnectionRefusedError: [Errno 111] Connection refused
```

Apparently it is trying to send an email?  But the docs don't have anything about setting up email env vars.

**Comment by guillaumevincent** [comment]
What was your command?

**Comment by edouard-lopez** [comment]
Your stacktrace shows error come from Django itself, not the backend's app.

**Comment by edouard-lopez** [comment]
Can't reproduce with:

### Command

    docker-compose build
    docker-compose up -d

### LessPass

**version**

    $ git rev-parse HEAD
    0f4a82489028bdee5daa0342a9998ef31a30323e

**submodules' version**
```
$ git submodule foreach git rev-parse HEAD
Entering 'backend'
2b3841033751d586f6180b1b0ff4ea574a0737c4
Entering 'cli'
2d01dd16b12f455ac699b4b8e5b38779cbec44f3
Entering 'core'
02794899e86cd1af470ed631018cf708eced0330
Entering 'cozy'
3b3e1540f8b9fb776415001af2518ad52ee7f41e
Entering 'frontend'
e79596709c3245f44491cc8de7be06c0b32a1450
Entering 'nginx'
ed80a2f89204c8c2c99eb1194586fcc5b3929135                                                                                                                                                                                                     Entering 'pure'
fc21a0612f1300fa383d84fa65d1fab84a1a23f5                                                                                                                                                                                                     Entering 'sandbox'
f99140f670c82f38626f68d5a5c7cf6047951dd5
Entering 'webextension'
b1529bc97927d052a520a583d6b1231e5b3ab623
```

### Env
**docker**

    $ docker --version
    Docker version 17.03.1-ce, build c6d412e

**docker-compose**

    $ docker-compose --version
    docker-compose version 1.11.2, build dfed245

**docker images**

    $ docker images
    REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
    lesspass_nginx      latest              d620aac0c54d        3 minutes ago       114 MB
    lesspass_backend    latest              f149dd4f6690        6 minutes ago       351 MB
    lesspass_frontend   latest              5cbd2adae0bc        9 minutes ago       344 MB

**Comment by guillaumevincent** [comment]
I understand, I think @maxguru you have not set the SMTP info in the env file.
I will put here an example of the production config.

**Comment by guillaumevincent** [comment]
You should edit your .env file and add the following variables

```
DEFAULT_FROM_EMAIL="LessPass" <contact@lesspass.com>
EMAIL_HOST=...
EMAIL_HOST_USER=...
EMAIL_HOST_PASSWORD=...
EMAIL_PORT=587
EMAIL_USE_TLS=1
```

**Comment by maxguru** [comment]
@guillaumevincent, I set up maicatcher with those env vars and when I try to use the lesspass Chrome ext, it is sending an email with a bunch of debug data to guillaume@oslab.fr.  It contains the following error message,
```
...
Report at /api/auth/register/
Invalid HTTP_HOST header: '192.168.10.21:8000'. You may need to add '192.168.10.21' to ALLOWED_HOSTS.
...
```

I am running this container on the internal network (hence the private subnet).  I am using 'http://192.168.10.21:8000' as the LessPass URL.

**Comment by maxguru** [comment]
I forgot I had to go through the nginx container.  I tried that (it is running on a different port) and I used the correct FQDN but it is still not registering an account.  Something else is wrong..

**Comment by guillaumevincent** [comment]
@maxguru LessPass is expecting a domain name, so add in your `/etc/hosts` a DNS entry

    192.168.10.21 mylesspass.com

And then run the installation:

    bash <(curl -s https://raw.githubusercontent.com/lesspass/lesspass/master/lesspass.sh) mylesspass.com

Visit https://mylesspass.com

In webextension enter in LessPass url: `https://mylesspass.com`

**Comment by guillaumevincent** [comment]
@maxguru you can also add `DJANGO_DEBUG=1` to avoid the need of SMTP server, every mail are printed in your console. `docker-compose logs -f`
