### ISSUE TITLE
Getting Error while Installing Lesspass on Self Hosted Server

### ISSUE THREAD

**Issue by AliAzizAhmed** [lesspass/lesspass#382]
Bonjour LessPass Team,

I am having issues while installing a self hosted lesspass server as there are no relevant documents available to do it, therefore appreciate your support in it.

Server/Protocol Details:
**OS: Centos 7
docker-compose version 1.23.2, build 1110ad0
docker-py version: 3.7.0
CPython version: 2.7.5
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017**

I have installed the docker and docker-compose from the link ( https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Install-Docker-and-Docker-Compose-(Centos-7) ) and after downloading the lesspass 6.1.0 I get the error "**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9awkb3/lesspass/**"

Deatiled error is below,

**[root@localhost admin]# pip install --user --upgrade lesspass==6.1.0
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting lesspass==6.1.0
  Downloading https://files.pythonhosted.org/packages/0b/1f/17ed5b00d5ff059996229d775b98eb80683e7f1668c18be8c7921c8db1d6/lesspass-6.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9awkb3/lesspass/setup.py", line 4, in <module>
        from lesspass.help import get_long_help
      File "lesspass/help.py", line 60
    SyntaxError: Non-ASCII character '\xc2' in file lesspass/help.py on line 61, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9awkb3/lesspass/**

Appreciate if someone guide me in this regard, I have used all the suggestions as mentioned in Issue 140 but it didn't resolve my case yet.

Cheers

AAA

**Comment by AliAzizAhmed** [comment]
Hi @guillaumevincent,

Thanks will wait and hope it comes out soon.

Thanks
AAA

**Comment by AliAzizAhmed** [comment]
Hi @guillaumevincent,

Thanks I have update it and below is the output, I was able to successfully install lesspass, now can you let me know how to get it working with my browser? I am looking for a document but couldn't find any on the subject.

I try to open my Linux box IP in the browser but nothing comes up but the message appears that IP didn't send any data. I am new in using the Lesspass stuff so need some guidance on it.

[root@localhost lesspass]# docker-compose version
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 3.4.9
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

[root@localhost ]# python3 -m pip install --user lesspass
Collecting lesspass
  Downloading https://files.pythonhosted.org/packages/6d/66/056644a6365d3bc12e29202f1a81c053364e26cc975a1078fc4bded1fc12/lesspass-6.1.0-py3-none-any.whl
Installing collected packages: lesspass
  The script lesspass is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed lesspass-6.1.0

Thanks
AAA

**Comment by edouard-lopez** [comment]
No need to be `root` to install lesspass CLI, this should solve the `$PATH` related warning. 
Otherwise, add `/root/.local/bin` to  the root user `$PATH` as show in the error.

I'm  it sure why you try to install the CLI, the self-hosted container are here to provide a backend and database to store your saved profiles.

**Comment by edouard-lopez** [comment]
The current readme is only addressing the CLI install.

:warning: I haven't tested this since I'm on my mobile. 
What you want to do to install the self-hosted servers is something like :

```
git clone git@github.com:lesspass/lesspass.git
cd lesspass/containers/
docker-compose up ./
```
Then connect to your containers ip on port `80` or `443` for HTTPS.

**Comment by AliAzizAhmed** [comment]
Hi @edouard-lopez,

**I forgot to add the below abstract in my previous one,**

[root@localhost home]# python3 -m pip install --user lesspass
Requirement already satisfied: lesspass in /root/.local/lib/python3.7/site-packages (6.1.0)

**After running the suggested git clone I get the a permission deny, [Permission denied (publickey).
fatal: Could not read from remote repository.], please see below**

[root@localhost lib]# git clone git@github.com:lesspass/lesspass.git
Cloning into 'lesspass'...
The authenticity of host 'github.com (192.30.255.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
RSA key fingerprint is MD5:16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.255.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Thanks
AAA

**Comment by guillaumevincent** [comment]
Wait a little before installing anything from source code, as I said, the work is in progress.
As @edouard-lopez said the containers are in the containers folder of the lesspass source code.
Clone https://github.com/lesspass/lesspass and play with it. 


Are you familiar with git and docker and docker-compose?
If no wait a little before we provide a one liner installer.

**Comment by AliAzizAhmed** [comment]
Hi @guillaumevincent,

When is the new source code expected to be available?

Thanks
AAA

**Comment by guillaumevincent** [comment]
Because it's a pet project, I work on it when I have some time. So for now I don't have any date.

You can look at the old docker-compose.prod.yml at the root directory

**Comment by ipiazza** [comment]
hello @guillaumevincent, 
is the one liner installer for docker-compose available?
I am trying to self-host lesspass using the docker-compose.yml file under the container directory of the repository but I am getting errors from the webserver container. I guess it is cause I have to populate with some values the environment variables inside the yaml file but I don't know what values I should set them to.

Can you please provide some indications on how to do that?

Thanks!
