### ISSUE TITLE
Frontend: Error: no writecb in Transform class

### ISSUE THREAD

**Issue by xiaochao** [lesspass/lesspass#39]
When i run npm run build command.Exception happed.

```
[11:42:01] Starting 'build'...
[11:42:01] Starting 'lesspass'...
[11:42:01] Starting 'images'...
[11:42:01] Starting 'favicon'...
[11:42:01] Finished 'build' after 109 ms
[11:42:01] Starting 'default'...
[11:42:01] Finished 'default' after 20 μs
[11:42:13] Finished 'lesspass' after 12 s
[11:42:13] Finished 'images' after 12 s
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: no writecb in Transform class
    at afterTransform (/Users/simon/Project/lesspass/frontend/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:74:40)
    at TransformState.afterTransform (/Users/simon/Project/lesspass/frontend/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at /Users/simon/Project/lesspass/frontend/node_modules/favicons/index.js:238:17
    at /Users/simon/Project/lesspass/frontend/node_modules/async/lib/async.js:52:16
    at Immediate._onImmediate (/Users/simon/Project/lesspass/frontend/node_modules/async/lib/async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/0.12.4/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! lesspass-frontend@1.0.2 build: `rm -rf dist && gulp && rm dist/index.html`
npm ERR! Exit status 1
```

**Comment by guillaumevincent** [comment]
Hi @xiaochao,
It looks like a problem with gulp and node.
you are using node `v5.4.1` and the current node v5 is `v5.7.0`
LessPass is tested with node LTS 6

Can you try upgrading node and retry ?

**Comment by xiaochao** [comment]
thanks. i will try to upgrade and do it again.

**Comment by guillaumevincent** [comment]
I close. 
Feel free to post on this thread to ask for extra help.
