### ISSUE TITLE
App crashes when opening settings

### ISSUE THREAD

**Issue by haary** [lesspass/lesspass#455]
When hitting the settings gear lesspass crashes

Version: 8.1.1 (F-Droid)
ROM: Resurrection Remix 7.0.2 (Android 9), no GApps, using microG
Phone: Xiaomi Redmi Plus 5 (Vince)

```
time: 1563908369367
msg: com.facebook.react.bridge.NoSuchKeyException: lineNumber
stacktrace: com.facebook.react.bridge.NoSuchKeyException: lineNumber
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:124)
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:128)
	at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:182)
	at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:193)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
	at java.lang.Thread.run(Thread.java:764)
```

Version 3.1.6 from F-Droid doesn't crash

**Comment by edouard-lopez** [comment]
I reproduce on my phone with Android `9.0`:
* `8.0.2` was working fine
* `8.1.1` break

**Comment by guillaumevincent** [comment]
Yeah I don't control the release of F-Droid
8.0.2 is the version on the Android store.

I need to work on this.
Since we are on mono repo there is one version number for everything.

I need to add more tests on the Android version to catch those bugs before we publish a version on Android Store or FDroid.
Because it's a manual process for Android Store and partially manual on FDroid.

Your feeling @Rudloff on this one?

**Comment by Rudloff** [comment]
Auto-update is not enabled for this app in F-Droid (because of some technical limitations), so I manually add the latest release from time to time.
We usually assume the latest tag to be stable, but maybe I should check if it was published on Google Play first?

**Comment by edouard-lopez** [comment]
@guillaumevincent might be interested by [`Detox`](https://github.com/wix/Detox)
> Gray box end-to-end testing and automation framework for mobile apps

**Comment by guillaumevincent** [comment]
Best is to go to the continuous delivery process. To do so yes we need to add more tests. A tag should represent a valid version of LessPass for every projects. So we can assume latest tag == stable @Rudloff 

Let me check if I can create some simple test to catch those errors before pushing it into Android Store and FDroid

**Comment by guillaumevincent** [comment]
I build the app for every release, let assume is enough for now to catch those bugs
