### ISSUE TITLE
9.0.2 crash on Android

### ISSUE THREAD

**Issue by Rudloff** [lesspass/lesspass#482]
If I build 9.0.2 from source, it crashes at launch with this error:
```
10-22 21:16:55.611 30152 30187 E AndroidRuntime: FATAL EXCEPTION: create_react_context
10-22 21:16:55.611 30152 30187 E AndroidRuntime: Process: com.lesspass.android, PID: 30152
10-22 21:16:55.611 30152 30187 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
10-22 21:16:55.611 30152 30187 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
10-22 21:16:55.611 30152 30187 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
10-22 21:16:55.611 30152 30187 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
10-22 21:16:55.611 30152 30187 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
10-22 21:16:55.611 30152 30187 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
10-22 21:16:55.611 30152 30187 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
10-22 21:16:55.611 30152 30187 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:949)
10-22 21:16:55.611 30152 30187 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by guillaumevincent** [comment]
yes, I didn't take the time to fix this, 9.0.2 was to fix an issue on the web extension
I will try to fix this this week.

**Comment by guillaumevincent** [comment]
Can you test again on master?
I migrate the mobile app and use react-native 0.61.

If it works, I will tag a new version and send it on the Android store

**Comment by Rudloff** [comment]
I tried to build f93f8c92fdce576b7d61a75aa67740de7380a246 and it seems to run correctly. Thanks!

**Comment by guillaumevincent** [comment]
ok closing this one and preparing a new version
