### ISSUE TITLE
Can't copy the password to clipboard (lesspass 9.1.2)

### ISSUE THREAD

**Issue by TheWiresharkGuy** [lesspass/lesspass#487]
Hi !

I can't copy the output of lesspass 9.1.2 (python cli version) to clipboard on Windows 10
NB : lesspass 8.1.1 was the previous version that i used and was working fine.
``` 
PS > lesspass -v
9.1.2
PS > lesspass -c test
Master Password:
Copy failed, we are sorry
Can you send us an email at contact@lesspass.com

--------------------------------------------------------------------------------
Object: [LessPass][cli] Copy issue on Windows
Hello,
I got an issue with LessPass cli software.

Traceback (most recent call last):
  File "c:\users\[...]\lib\site-packages\lesspass\core.py", line 43, in main
    copy(generated_password)
  File "c:\users\[...]\lib\site-packages\lesspass\clipboard.py", line 49, in copy
    p.communicate(input=text)
  File "c:\python38\Lib\subprocess.py", line 1009, in communicate
    self._stdin_write(input)
  File "c:\python38\Lib\subprocess.py", line 958, in _stdin_write
    self.stdin.write(input)
TypeError: a bytes-like object is required, not 'str'
--------------------------------------------------------------------------------
```

**Comment by guillaumevincent** [comment]
What is your version of python you are using?
`python --version`

**Comment by TheWiresharkGuy** [comment]
@guillaumevincent 

Python 3.8.0
